import type { User, EmergencyContact, Emergency, NearbyService, Notification } from "./types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "john@example.com",
    name: "John Doe",
    phone: "+1 555-0123",
    role: "user",
    medicalInfo: {
      bloodType: "O+",
      allergies: ["Penicillin"],
      medications: ["Aspirin"],
      conditions: ["Asthma"],
      emergencyNotes: "Carries inhaler",
    },
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "admin-1",
    email: "admin@hotel.com",
    name: "Sarah Admin",
    phone: "+1 555-0456",
    role: "admin",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "responder-1",
    email: "responder@ngo.org",
    name: "Mike Responder",
    phone: "+1 555-0789",
    role: "responder",
    createdAt: new Date("2024-02-01"),
  },
]

export const mockEmergencyContacts: EmergencyContact[] = [
  {
    id: "contact-1",
    userId: "user-1",
    name: "Jane Doe",
    phone: "+1 555-1111",
    email: "jane@example.com",
    relationship: "Spouse",
    isPrimary: true,
    notifyOnEmergency: true,
  },
  {
    id: "contact-2",
    userId: "user-1",
    name: "Robert Doe",
    phone: "+1 555-2222",
    email: "robert@example.com",
    relationship: "Brother",
    isPrimary: false,
    notifyOnEmergency: true,
  },
  {
    id: "contact-3",
    userId: "user-1",
    name: "Dr. Smith",
    phone: "+1 555-3333",
    relationship: "Doctor",
    isPrimary: false,
    notifyOnEmergency: false,
  },
]

export const mockEmergencies: Emergency[] = [
  {
    id: "emergency-1",
    userId: "user-1",
    userName: "John Doe",
    type: "sos",
    status: "active",
    location: {
      lat: 40.7128,
      lng: -74.006,
      accuracy: 10,
      timestamp: new Date(),
      address: "123 Main St, New York, NY",
    },
    locationHistory: [
      {
        lat: 40.7128,
        lng: -74.006,
        timestamp: new Date(Date.now() - 60000),
      },
      {
        lat: 40.7129,
        lng: -74.0061,
        timestamp: new Date(Date.now() - 30000),
      },
      {
        lat: 40.713,
        lng: -74.0062,
        timestamp: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 300000),
    updatedAt: new Date(),
  },
  {
    id: "emergency-2",
    userId: "user-2",
    userName: "Alice Smith",
    type: "silent",
    status: "responding",
    location: {
      lat: 40.758,
      lng: -73.9855,
      accuracy: 15,
      timestamp: new Date(),
      address: "Times Square, New York, NY",
    },
    locationHistory: [],
    createdAt: new Date(Date.now() - 600000),
    updatedAt: new Date(),
    responderId: "responder-1",
    responderName: "Mike Responder",
  },
]

export const mockNearbyServices: NearbyService[] = [
  {
    id: "hospital-1",
    name: "City General Hospital",
    type: "hospital",
    location: {
      lat: 40.715,
      lng: -74.008,
      timestamp: new Date(),
      address: "500 Hospital Ave, New York, NY",
    },
    phone: "+1 555-HOSP",
    address: "500 Hospital Ave, New York, NY 10001",
    distance: 0.8,
    isOpen: true,
  },
  {
    id: "hospital-2",
    name: "Downtown Medical Center",
    type: "hospital",
    location: {
      lat: 40.72,
      lng: -74.0,
      timestamp: new Date(),
      address: "200 Medical Blvd, New York, NY",
    },
    phone: "+1 555-MEDC",
    address: "200 Medical Blvd, New York, NY 10002",
    distance: 1.2,
    isOpen: true,
  },
  {
    id: "police-1",
    name: "1st Precinct Police Station",
    type: "police",
    location: {
      lat: 40.711,
      lng: -74.004,
      timestamp: new Date(),
      address: "100 Police Plaza, New York, NY",
    },
    phone: "911",
    address: "100 Police Plaza, New York, NY 10001",
    distance: 0.5,
    isOpen: true,
  },
  {
    id: "police-2",
    name: "5th Precinct Police Station",
    type: "police",
    location: {
      lat: 40.718,
      lng: -73.998,
      timestamp: new Date(),
      address: "150 Elizabeth St, New York, NY",
    },
    phone: "911",
    address: "150 Elizabeth St, New York, NY 10013",
    distance: 1.0,
    isOpen: true,
  },
  {
    id: "ngo-1",
    name: "SafeHaven Crisis Center",
    type: "ngo",
    location: {
      lat: 40.714,
      lng: -74.002,
      timestamp: new Date(),
      address: "75 Safety Lane, New York, NY",
    },
    phone: "+1 555-SAFE",
    address: "75 Safety Lane, New York, NY 10001",
    distance: 0.6,
    isOpen: true,
  },
  {
    id: "ngo-2",
    name: "Women's Emergency Shelter",
    type: "ngo",
    location: {
      lat: 40.722,
      lng: -74.005,
      timestamp: new Date(),
      address: "300 Support Ave, New York, NY",
    },
    phone: "+1 555-HELP",
    address: "300 Support Ave, New York, NY 10002",
    distance: 1.5,
    isOpen: true,
  },
  {
    id: "fire-1",
    name: "Engine Company 10",
    type: "fire",
    location: {
      lat: 40.7105,
      lng: -74.0087,
      timestamp: new Date(),
      address: "124 Liberty St, New York, NY",
    },
    phone: "911",
    address: "124 Liberty St, New York, NY 10006",
    distance: 0.4,
    isOpen: true,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    title: "Emergency Alert Sent",
    message: "Your SOS alert has been sent to your emergency contacts",
    type: "emergency",
    read: false,
    createdAt: new Date(Date.now() - 60000),
    emergencyId: "emergency-1",
  },
  {
    id: "notif-2",
    userId: "user-1",
    title: "Location Updated",
    message: "Your location has been shared with responders",
    type: "info",
    read: true,
    createdAt: new Date(Date.now() - 300000),
  },
]
